apiVersion: 1

datasources:
  - name: Supply Chain TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
